#!/usr/bin/env python3
import os
import sys
import json
import re

def main(argv):
    PAT = re.compile(r'^\s*(\S+)\s*(\d+)/(\d+)\s*(\d+\.\d+):\s*(\S+):')
    if len(argv) > 0:
        fp = open(argv[0], 'r')
    else:
        fp = sys.stdin
    trace = []
    for line in fp:
        m = PAT.search(line)
        if not m:
            continue
        (comm, pid, tid, ts, probe) = m.groups()
        pid = int(pid)
        tid = int(tid)
        ts = int(1e6*float(ts))
        probe = re.sub(r'^[^:]+:probe_', '', probe)
        ph = 'I'
        if probe.startswith('enter_'):
            ph = 'B'
            probe = probe[len('enter_'):]
        elif probe.startswith('exit_'):
            ph = 'E'
            probe = probe[len('exit_'):]
        event = {
            'ph': ph,
            'ts': ts,
            'pid': pid,
            'tid': tid,
            'name': probe,
        }
        trace.append(event)
    json.dump(trace, sys.stdout, indent=1)

if __name__ == "__main__":
    main(sys.argv[1:])
